### ISSUE TITLE
Feature: User can view list of characters

### ISSUE THREAD

**Issue by brian-luong** [brian-luong/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Feature: User can view list of characters alphabetically

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Characters are sorted in alphabetical order by the first letter of their first name

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/64977584/153537351-b4df482c-2b99-48ae-a88f-84ae0f7f692e.png)
![image](https://user-images.githubusercontent.com/64977584/153537369-798a1824-ad47-4938-bbba-d1885fbdb900.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Site is responsive on both desktop and mobile
- [x] create a GET request to pull in list of characters
- [x] Display list in alphabetical order
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
