### ISSUE TITLE
Feature: User can sort list of characters by first name starting with first letter

### ISSUE THREAD

**Issue by brian-luong** [brian-luong/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sort list of characters by first name starting with first letter

## 📐 Functionality

User can sort for characters by first name by clicking on a letter.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/64977584/153537390-2733aa31-1124-428b-bf1f-45bfe6d26ee8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Clicking on letter will sort by characters with first names that start with that letter
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
