### ISSUE TITLE
Feature: User can search for a harry potter character in a search bar

### ISSUE THREAD

**Issue by brian-luong** [brian-luong/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a harry potter character in a search bar

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

As user types in search bar, it will start to display search results. Once you click on a result, a modal will display showing me details about the character.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/64977584/153537412-0b2b5397-e4de-4903-be29-44254b05c697.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] as user types in search bar, there's a dropdown and displays search results
- [ ] when user selects a result and hits search, a modal will popup displaying the details of character
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
