### ISSUE TITLE
Feature: User can view details of a Harry Potter Character

### ISSUE THREAD

**Issue by brian-luong** [brian-luong/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details of a Harry Potter Character 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on an image or name, a modal will popup that displays more details about a character

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/64977584/153536133-f8500915-0736-4ce3-b5e3-ddd4af984a14.png)
![image](https://user-images.githubusercontent.com/64977584/153536146-d2a3cde2-7083-4873-bf95-1ff829b1bd3f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] addEventlistener for images and name
- [ ] display a modal that contains details about the character
- [ ] add an x button
- [ ] add a star icon
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
