### ISSUE TITLE
Feature: User can save a character to their favorites list

### ISSUE THREAD

**Issue by brian-luong** [brian-luong/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a character to their favorites list

## 📐 Functionality

User can save a character to their favorites list by click on the star icon within a character's modal

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/64977584/153536459-0663999e-b157-440b-9193-af3386078138.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add event listener for star icon
- [ ] set "favorites" property to true if user clicks on star icon
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
