### ISSUE TITLE
Feature: User can view their favorite characters.

### ISSUE THREAD

**Issue by brian-luong** [brian-luong/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their favorite characters.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After user has favorited a character, use can view all of their favorites by clicking on the My favorite characters on the nav.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/64977584/153536968-c53c8adf-599f-4e80-8fd1-04b35e9968b0.png)
![image](https://user-images.githubusercontent.com/64977584/153536995-437a1fd3-973e-4666-9187-3fa57422a71d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Render all character entries with the "favorite" property set to true
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
